### ISSUE TITLE
Setup CircleCI or Travis

### ISSUE THREAD

**Issue by scottkidder** [adopted-ember-addons/ember-pikaday#201] opened 2018-10-01 11:50 UTC
I'll be happy to set this up, but is there a consensus on what service we might prefer?

**Comment by alexlafroscia** [comment] 2018-10-01 19:42
I think we should stick with Travis, seeing as that's the "default" for Ember apps (and an Ember app itself!)

I've been trying to dig into why CI seems broken, and your help would be greatly appreciated. For some reason I can't view the repo on travis-ci.com:

<img width="693" alt="screen shot 2018-10-01 at 12 19 06 pm" src="https://user-images.githubusercontent.com/1645881/46311515-51dcb900-c577-11e8-89b3-327c591a5660.png">

travis-ci.org actually does seem to have the repo, but the builds are not being run for PRs or against master right now:

https://travis-ci.org/adopted-ember-addons/ember-pikaday

I've reached out to their Twitter to see if we can get to the bottom of what's going. My hunch is that transferring the repo between orgs has confused their system for some reason.

I would prefer we get it working through travis-ci.com if we can, because the Github integration is better, but I would take either of none at all.

**Comment by alexlafroscia** [comment] 2018-10-01 19:44
I was able to manually trigger a build from `master`... I guess that's something of a start?

https://travis-ci.org/adopted-ember-addons/ember-pikaday/builds/435800682

**Comment by alexlafroscia** [comment] 2018-10-01 20:15
I _think_ the problem is just that travis-ci.org is still looking for events from the old repo to kick off builds automatically and such... I'm not sure what we can do about that, though.

**Comment by scottkidder** [comment] 2018-10-02 11:35
Hmm, https://travis-ci.org/profile/adopted-ember-addons implies that adopted-ember-addons doesn't exist as an organization on travis. Maybe https://github.com/travis-ci/travis-ci/issues/6602#issuecomment-247029548 ?

**Comment by alexlafroscia** [comment] 2018-10-02 17:36
Why do you say that? I can access the page you linked to.

**Comment by alexlafroscia** [comment] 2018-10-02 20:33
I contacted their support email to see if we can get their help figuring out what's going wrong here.

**Comment by pepke41** [comment] 2018-10-05 06:03
A build was kicked off on my pr #207 so I think you can close the issue.

**Comment by alexlafroscia** [comment] 2018-10-05 06:04
Indeed! I worked with a support person from Travis and they were able to walk me through getting the hooks set up again.

**Closed by alexlafroscia** 2018-10-05 06:04 UTC
Labels: question

**Comment by alexlafroscia** [comment] 2018-10-10 16:16
They migrated this repo over to travis-ci.com, so we should get the nicer experience around having the "checks" tab populated in each pull-request now 🎉
