### ISSUE TITLE
Close inputless by clicking anywhere on page

### ISSUE THREAD

**Issue by Mikeg542** [adopted-ember-addons/ember-pikaday#130] opened 2017-01-31 14:41 UTC
We have an inputless pikaday that starts hidden and shows on a click of a button. We are trying to figure out why clicking outside of the calendar is not hiding it as that appears to be a pikaday default feature. 

If it is not, is there a way to send the pikaday object to a listener function and have it hide onClick ourselves?

**Comment by duizendnegen** [comment] 2017-01-31 16:59
This is surprising to me - it should work by default, like Pikaday. Are you sure there's no other CSS layer overlaying this? If so, could you reproduce this in an empty repo?

**Comment by Mikeg542** [comment] 2017-01-31 17:22
It's pretty integrated with some proprietary stuff, so I'm limited in replicating. It is currently set up like so:

`<a href="#" {{action 'showDates'}} id="test">
    <h3>Availability <i class="fa fa-calendar-check-o" aria-hidden="true"></i></h3>
    <h4>(SHOW FORMATTED DATE STUFF)</h4>
    {{#if datePicker}}
        <div class="date-picker" id="menu" {{action 'dropDown'}}>
            {{pikaday-inputless onSelection=(action 'setAvailability') format="YYYY-MM-DD"}}
        </div>
    {{/if}}
</a>`

With the ember action:

```
showDates() {
            let showDates = this.get('datePicker');
            this.set('datePicker', !showDates);
}
```
The functionality is clicking the a#test opens up the calendar, where you select a date and time and it populates the h4 within the a. Toggling with the a works fine, but clicking outside is being overwritten in some way.

**Comment by Mikeg542** [comment] 2017-01-31 18:37
We did manage to find a solution with jQuery, but if we could get the default functionality working it would be preferable!

**Comment by duizendnegen** [comment] 2017-01-31 19:18
I'm still not 100% convinced it's a bug on our side (it might be! but this is not the way I use it myself & I can't say) so I'd suggest to get a clean repo (an Ember project just with `ember-pikaday`) and see what happens there, then optionally submit a PR with a fix

Thanks!

**Comment by alexlafroscia** [comment] 2018-10-01 20:40
Going to close this until @Mikeg542 responds with a reproduction

**Comment by AleksandrBorovkov** [comment] 2019-07-26 19:44
@alexlafroscia 
Here is clean branch with reproduction. 
https://github.com/AleksandrBorovkov/ember-test2

**Comment by alexlafroscia** [comment] 2019-08-01 01:30
So to clarify: you want to close the picker when clicking outside of it? Something would need to set `showPika` back to `false` -- this wouldn't happen implicitly.

If I'm reading the source of `pikaday` correctly, the dismiss-on-click-outside is actually listening for a `blur` event on the form field

https://github.com/Pikaday/Pikaday/blob/5c1a7559be0373c93f971366abd6ddff82b18ed0/pikaday.js#L613

I'm not sure what the right way to tackle this for the `pikaday-inputless` component would be; there isn't really a specific element that we could attach to a `blur` event on since the input element itself is invisible. I'm hesitant to have this add-on introduce some kind of transparent element covering the entire screen that we could listen to a `click` event on.

One solution that I came up with was bringing in another add-on called [`ember-click-outside`](https://github.com/zeppelin/ember-click-outside), which I used like this in the reproduction repo that @AleksandrBorovkov provided:

```hbs
{{#if showPika}}
  {{#click-outside action=(action "togglePika")}}
    {{pikaday-inputless value="2017-07-07"}}
  {{/click-outside}}
{{/if}}
```

This had the click-outside behavior that was requested without having to introduce anything to `ember-pikaday` at all!

**Closed by alexlafroscia** 2019-08-01 01:30 UTC
