### ISSUE TITLE
DEPRECATION: ember-cli-babel 5.x has been deprecated.

### ISSUE THREAD

**Issue by AdminDev826** [adopted-ember-addons/ember-pikaday#198] opened 2018-09-28 14:21 UTC
Getting the warning:
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: bai-ui -> ember-pikaday -> ember-cli-babel
"ember-pikaday": "^2.2.4"
"ember-cli": "^3.1.4"

**Comment by jrjohnson** [comment] 2018-09-28 15:41
Duplicate of #175

**Comment by alexlafroscia** [comment] 2018-09-28 18:57
Closing because it's a duplicate. I will publish a fix for this to NPM soon!

**Closed by alexlafroscia** 2018-09-28 18:57 UTC
